// This file contains database-specific types that are auto-generated by Supabase
// and should not be modified manually.

declare global {
  namespace Database {
    interface Tables {
      // Add any database table interfaces here if needed
    }
  }
}

export {};
